# Reference:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates

trigger:
- master


jobs:

- template: azure-pipelines-job-template.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-18.04'

- template: azure-pipelines-job-template.yml
  parameters:
    name: macOS
    vmImage: 'macOS-10.13'

- template: azure-pipelines-job-template.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'

