[tool.towncrier]

package = "wires"
package_dir = "src"
filename = "CHANGELOG.rst"
issue_format = "`#{issue} <https://github.com/tmontes/python-wires/issues/{issue}>`_"
title_format = "{name} {version}"
directory = "docs/newsfragments"
underlines = ["-", "^"]

	[[tool.towncrier.type]]
	directory = "deprecate"
	name = "Deprecations"
	showcontent = true

	[[tool.towncrier.type]]
	directory = "enhancement"
	name = "Enhancements"
	showcontent = true

	[[tool.towncrier.type]]
	directory = "bug"
	name = "Bug Fixes"
	showcontent = true

	[[tool.towncrier.type]]
	directory = "other"
	name = "Other Changes"
	showcontent = true
